<meta charset="utf-8" />
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!-- bootstrap & fontawesome -->
<link rel="stylesheet" href="{{ static_url('assets/css/bootstrap.min.css?_v=')~assetsVersion }}" />
<link rel="stylesheet" href="{{ static_url('assets/font-awesome/4.5.0/css/font-awesome.min.css?_v=')~assetsVersion }}" />

<!-- page specific plugin styles -->

<!-- text fonts -->
<!--<link rel="stylesheet" href="{{ static_url('assets/css/fonts.googleapis.com.css?_v=')~assetsVersion }}" />-->

<!-- ace styles -->
<link rel="stylesheet" href="{{ static_url('assets/css/ace.min.css?_v=')~assetsVersion }}" />

<!--[if lte IE 9]>
	<link rel="stylesheet" href="{{ static_url('assets/css/ace-part2.min.css?_v=')~assetsVersion }}" class="ace-main-stylesheet" />
<![endif]-->
<!--<link rel="stylesheet" href="{{ static_url('assets/css/ace-skins.min.css?_v=')~assetsVersion }}" />-->
<!--<link rel="stylesheet" href="{{ static_url('assets/css/ace-rtl.min.css?_v=')~assetsVersion }}" />-->

<!--[if lte IE 9]>
  <link rel="stylesheet" href="{{ static_url('assets/css/ace-ie.min.css?_v=')~assetsVersion }}" />
<![endif]-->
<link href="{{ static_url('assets/css/style.css?_v=')~assetsVersion }}" rel="stylesheet" />

<script src="{{ static_url('assets/js/jquery-2.1.4.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('assets/js/bootstrap.min.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('assets/js/ace-extra.min.js?_v=')~assetsVersion }}"></script> 
<script src="{{ static_url('assets/js/ace.min.js?_v=')~assetsVersion }}"></script>

<script src="{{ static_url('treegrid/js/jquery.treegrid.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('assets/js/ace-elements.min.js?_v=')~assetsVersion }}"></script> 
<script src="{{ static_url('assets/js/public.js?_v=')~assetsVersion }}"></script>
<script src="{{ static_url('tinymce/tinymce.min.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript" src="{{ static_url('assets/js/master.js?_v=')~assetsVersion }}"></script>
