<div class="navbar-container ace-save-state" id="navbar-container">
    <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" data-target="#sidebar">
        <span class="sr-only">Toggle sidebar</span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>

        <span class="icon-bar"></span>
    </button>

    <div class="navbar-header pull-left">
        <a href="{{ url('dashboard/index') }}" class="navbar-brand">
            <small>
                <i class="icon-leaf"></i>
                {{title}}
            </small>
        </a>
    </div>

    <div class="navbar-header pull-right" role="navigation">
        <ul class="nav ace-nav">
            <li class="light-blue dropdown-modal">
                <a data-toggle="dropdown" href="#" class="dropdown-toggle" aria-expanded="false">
                    <span class="user-info">
                        <small>{{ trans('welcome') }},</small>
                        {{userinfo['username']}}
                    </span>
                    <i class="ace-icon fa fa-caret-down"></i>
                </a>
                <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-yellow dropdown-caret dropdown-close">
                    <li>
                        <a href="{{ url('account/profile') }}">
                            <i class="ace-icon fa fa-user"></i>
                            {{ trans('profile') }}
                        </a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="{{url('auth/logout')}}">
                            <i class="ace-icon fa fa-power-off"></i>
                            {{ trans('logout') }}
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
