<div class="error-container">
    <div class="well">
        <h1 class="grey lighter smaller">
            <span class="blue bigger-125">
                <i class="ace-icon fa fa-random">
                </i>
                {{ trans('error.no-permission') }}
            </span>
        </h1>
        <hr>
            <h3 class="lighter smaller">
                <i class="ace-icon fa fa-wrench icon-animated-wrench bigger-125">
                </i>
                {{ trans('message.no-permission') }}
            </h3>
            <div class="space">
            </div>
            <div>
                <ul class="list-unstyled spaced inline bigger-110 margin-15">
                    <li>
                        <i class="ace-icon fa fa-hand-o-right blue">
                        </i>
                        {{ trans('message.login-account-again') }}
                    </li>
                    <li>
                        <i class="ace-icon fa fa-hand-o-right blue">
                        </i>
                        {{ trans('message.contact-administrator') }}
                    </li>
                </ul>
            </div>
        </hr>
    </div>
</div>