<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('tags/index') }}">{{ trans('tag-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('tags/index') }}">{{ trans('tag-management') }}</a>
            <small>
                <i class="fa fa-angle-double-right"></i>
                {{ trans('label.view') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-7">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ trans('label.tag_list') }}</h3>
            </div>
            <div class="panel-body">
                <div class="tags-box">
                    {% if tagsList is not empty %}
                        <ul>
                            {% set tagclound=['label-success', 'label-warning', 'label-danger', 'label-info', 'label-inverse', 'label-pink', 'label-yellow', 'label-purple'] %}
                            {% for tagk,tag in tagsList %}
                                <li>
                                    <span class="label {{tagclound[array_rand(tagclound)]}} arrowed-in-right arrowed">
                                        <a href="{{ url('tags/index?id='~tag['id']) }}" title="{{ trans('label.edit') }}">
                                            {{tag['name']}}
                                        </a>
                                        <a href="javascript:void(0);" class="delete-tag" data-url="{{ url('tags/delete?id='~tag['id']) }}" title="{{ trans('label.delete') }}">
                                            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                                        </a>
                                    </span>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        {{ trans('label.no-data') }}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-5">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ trans('label.save') }}</h3>
            </div>
            <div class="panel-body" >
                <form action="{{url('tags/save')}}" method="post" class="form-horizontal" id="tag-form">
                    <div class="form-group">
                        <label for="tag-name" class="col-sm-2 control-label">{{ trans('label.name') }}</label>
                        <div class="col-sm-10">
                            <input type="text" name="name" value="{% if taginfo is not empty %}{{taginfo['name']}}{% endif %}"
                                   class="form-control" id="tag-name" placeholder="{{ trans('label.name') }}">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="tag-slug" class="col-sm-2 control-label">{{ trans('label.tag') }}</label>
                        <div class="col-sm-10">
                            <input type="text" name="slug" value="{% if taginfo is not empty %}{{taginfo['slug']}}{% endif %}"
                                   class="form-control" id="taginfo-slug" placeholder="{{ trans('label.tag') }}">
                            <span class="lbl">{{ trans('validate.alpha_dash') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            {% if taginfo['id'] is not empty %}
                                <input type="hidden" name="id" value="{{taginfo['id']}}" />
                                <button type="submit" id="tag-btn" class="btn btn-info btn-sm">{{ trans('label.save') }}</button>
                            {% else %}
                                <button type="submit" id="tag-btn" class="btn btn-info btn-sm">{{ trans('label.add') }}</button>
                            {% endif %}
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('.delete-tag').on('click', function(){
        var dataUrl = $.trim($(this).attr('data-url'));
        if(!window.confirm("{{ trans('alert.is-delete-selected') }}")){
            return false;
        }
        window.location.href = dataUrl;
    });

    $('#tag-btn').on('click', function(){
        var tagSlug = $.trim($('#tag-slug').val());
        var tagSlugPattern = /^[\w-]+$/i;
        if(tagSlug == true && !tagSlugPattern.test(tagSlug)){
            tips_message("{{ trans('validate.alpha_numeric_dash') }}");
            return false;
        }

        $('#tag-form').submit();
    });
</script>
