<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('menu/index') }}">{{ trans('menu-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('menu/index') }}">{{ trans('menu-management') }}</a>
            <small>
                <i class="fa fa-angle-double-right"></i>
                {{ trans('menu-list') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <div class="btn-panel">
            <a href="{{ url('menu/write') }}" class="btn btn-success btn-sm" role="button">{{ trans('label.add') }}</a>
            <a href="{{ url('menu/refresh') }}" class="btn btn-pink btn-sm" role="button">{{ trans('label.clear-cache') }}</a>
        </div>
        <div class="table-responsive">
            <table class="table tree-grid table-condensed table-hover" id="menu-table">
                <thead>
                <tr>
                    <th>{{ trans('label.name') }}</th>
                    <th>{{ trans('label.link') }}</th>
                    <th>{{ trans('label.category') }}</th>
                    <th>{{ trans('label.sort') }}</th>
                    <th>{{ trans('label.updated') }}</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                {% if menuList is not empty %}
                    <tbody>
                        {% for menu in menuList %}
                            {% if menu['parent'] is not empty %}
                                <tr class="treegrid-{{menu['id']}} treegrid-parent-{{menu['parent']}}">
                            {% else %}
                                <tr class="treegrid-{{menu['id']}}">
                            {% endif %}
                                <td>
                                    <a href="{{ url('menu/write?id='~menu['id']) }}">
                                        {{ menu['name'] }}
                                    </a>
                                </td>
                                <td>
                                    {% if menu['url'] is not empty %}
                                        {{ menu['url'] }}
                                    {% endif %}
                                </td>
                                <td>
                                    {% if menu['category'] is not empty %}
                                        {{ menu['category']['name'] }}
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="javascript:void(0);" class="menu-sort-block" data-name="sort"
                                       data-url="{{ url('menu/savesort') }}"
                                       data-pk="{{menu['id']}}" data-type="text"
                                       data-placement="top" data-title="{{ trans('label.sort') }}">
                                        {{ menu['sort'] }}
                                    </a>
                                </td>
                                <td>{{ menu['modify_time'] }}</td>  
                                <td>
                                    <a class="btn btn-xs btn-success" href="{{ url('menu/write?parentid='~menu['id']) }}">
                                        <i class="fa fa-plus bigger-120"></i>
                                    </a>
                                    <a class="btn btn-xs btn-info" href="{{ url('menu/write?id='~menu['id']) }}">
                                        <i class="fa fa-pencil bigger-120"></i>
                                    </a>
                                    <button class="btn btn-xs btn-danger delete-menu" data-url="{{ url('menu/delete?id='~menu['id']) }}">
                                        <i class="fa fa-trash-o bigger-120"></i>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                {% else %}
                    <tbody>
                    <tr>
                        <td colspan="8">{{ trans('label.no-data') }}</td>
                    </tr>
                    </tbody>
                {% endif %}
            </table>
        </div>
    </div>
</div>
<link href="{{ static_url('bootstrap-editable/css/bootstrap-editable.css?_v=')~assetsVersion }}" rel="stylesheet"/>
<script src="{{ static_url('bootstrap-editable/js/bootstrap-editable.min.js?_v=')~assetsVersion }}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.tree-grid').treegrid();
    });

    $.fn.editable.defaults.mode = 'popup';
    $('.menu-sort-block').editable({
        params:function(params){
            params.sort = params.value;
            params.id = params.pk;
            if(params.sort <= 0 || params.sort > 999){
                params.sort = 999;
            }
            return params;
        },
        success:function(response, value){
            if (typeof response !== 'object') response = JSON.parse(response);
            if (response.code == 1) {
                tips_message(response.message, 'success');
            } else {
                tips_message(response.message, 'error');
            }
            return true;
        },
        error:function(response){
            tips_message("{{ trans('alert.error-network') }}");
        },
        display:function(value){
            if(value <= 0 || value > 999){
                value = 999;
            }
            $(this).html(value);
        }
    });

    $('.delete-menu').on('click', function(){
        var dataUrl = $.trim($(this).attr('data-url'));
        if(!window.confirm("{{ trans('alert.is-delete-selected') }}")){
            return false;
        }
        window.location.href = dataUrl;
    });
</script>
