<?php

/**
 * Base62 encoding / decoding
 * @category ProjectShare
 * @copyright (c) open-source Phalcon framework
 * @license MIT License (c) 2017 8bit baseball
 */

namespace Lcd\App\Libs;

class Base62
{

    /**
     * Base62 encoding and decoding key, randomly generated by 10 digits, 26 uppercase letters and 26 lowercase letters 
     * @var string
     */
    const KEY = '9IwmZYy2aZf4qHBUwpfTwz5c2UuXkZr7d8rmzTaKwq899E3hj4GnwVc4ZUxrKm';

    /**
     * Get the key
     * @return string
     */
    protected static function get_key()
    {
        return self::KEY;
    }

    /**
     * Base62 encoding
     * @param $number
     * @param string $encode
     * @return string
     */
    public static function base62_encode($number, $encode = '')
    {
        while ($number > 0) {
            $key = self::get_key();
            $mod = bcmod($number, 62);
            $encode .= $key[$mod];
            $number = bcdiv(bcsub($number, $mod), 62);
        }
        return strrev($encode);
    }

    /**
     * Base62 decoding
     * @param $encode
     * @param int $number
     * @return int|string
     */
    public static function base62_decode($encode, $number = 0)
    {
        $length = strlen($encode);
        $baselist = array_flip(str_split(self::get_key()));
        for ($i = 0; $i < $length; $i++) {
            $number = bcadd($number, bcmul($baselist[$encode[$i]], bcpow(62, $length - $i - 1)));
        }
        return $number;
    }
}
