<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="og:title" content="HTML-CSS" />
    <meta name="og:description" content="nội dung hiển thị khi share" />
    <meta property="og:image" itemprop="thumbnailUrl" content="link hình share"/>
    <link rel="canonical" href="#" />
    <meta property="og:url" content="#" />
    <!--Favicon-->
    <link rel="shortcut icon" href="images/favicon.png" type="image/x-icon">
    <link rel="icon" href="{{ siteIcon }}" type="image/x-icon">
    <title>{{ siteTitle }}</title>
    <link href="{{ static_url('frontend/css/bootstrap.min.css?_v=')~assetsVersion }}" rel="stylesheet" />
    <link href="{{ static_url('frontend/css/style.css?_v=')~assetsVersion }}" rel="stylesheet" />
    <script type="text/javascript" src="{{ static_url('frontend/js/bootstrap.min.js?_v=')~assetsVersion }}"></script>
</head>