<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="javascript:void(0);">{{ trans('site-setting') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {{ trans('site-setting') }}
            <small>
                <i class="fa fa-angle-double-right"></i>
                {{ trans('basic-setting') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <ul class="nav nav-tabs">
            <li class="active">
                <a href="#apiinfo" data-toggle="tab">{{ trans('basic-setting') }}</a>
            </li>
            <li>
                <a href="#panelhome" data-toggle="tab">{{ trans('label.panel-home') }}</a>
            </li>
            <!-- <li>
                <a href="#acceinfo" data-toggle="tab">{{ trans('label.access') }}</a>
            </li> -->
        </ul>
        <div class="tab-content">
            <div class="tab-pane fade in active" id="apiinfo">
                <form action="{{url('options/savebase')}}" method="post" class="form-horizontal" id="base-options-form">
                    <div class="form-group">
                        <label for="site-name" class="col-sm-2 control-label">{{ trans('label.site_name') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="siteName" value="{% if options is not empty %}{{options['site_name']['op_value']}}{% endif %}"
                                   class="form-control" id="site-name" placeholder="{{ trans('label.site_name') }}">
                            <span class="form-tips">{{ trans('label.alpha_numeric_dash') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site-title" class="col-sm-2 control-label">{{ trans('label.site_title') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="siteTitle" value="{% if options is not empty %}{{options['site_title']['op_value']}}{% endif %}"
                                   class="form-control" id="site-title" placeholder="{{ trans('label.site_title') }}">
                            <span class="form-tips">{{ trans('message.site_title') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site_logo" class="col-sm-2 control-label">{{ trans('label.site_logo') }}</label>
                        <div class="col-sm-6">
                            <input type="text" name="site_logo" value="{% if options is not empty %}{{options['site_logo']['op_value']}}{% endif %}"
                                   class="form-control" id="site_logo" placeholder="{{ trans('label.site_logo') }}">
                        </div>
                        <div class="col-sm-1">
                            <a href="javascript:open_popup('/backend/filemanager/dialog.php?popup=1&amp;field_id=site_logo')" class="btn btn-warning btn-sm" type="button">Upload</a>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site_icon" class="col-sm-2 control-label">{{ trans('label.site_icon') }}</label>
                        <div class="col-sm-6">
                            <input type="text" name="site_icon" value="{% if options is not empty %}{{options['site_icon']['op_value']}}{% endif %}"
                                   class="form-control" id="site_icon" placeholder="{{ trans('label.site_icon') }}">
                        </div>
                        <div class="col-sm-1">
                            <a href="javascript:open_popup('/backend/filemanager/dialog.php?popup=1&amp;field_id=site_icon')" class="btn btn-warning btn-sm" type="button">Upload</a>
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="site-url" class="col-sm-2 control-label">{{ trans('label.site_address') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="siteUrl" value="{% if options is not empty %}{{options['site_url']['op_value']}}{% endif %}"
                                   class="form-control" id="site-url" placeholder="http://">
                        </div>
                    </div>
                    <div class="form-group ">
                        <label for="cdn-url" class="col-sm-2 control-label">{{ trans('label.cdn_address') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="cdnUrl" value="{% if options is not empty %}{{options['cdn_url']['op_value']}}{% endif %}"
                                   class="form-control" id="cdn-url" placeholder="http://">
                            <span class="form-tips">{{ trans('message.site_address') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site-keywords" class="col-sm-2 control-label">{{ trans('label.keyword') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="keywords" value="{% if options is not empty %}{{options['site_keywords']['op_value']}}{% endif %}"
                                   class="form-control" id="site-keywords" placeholder="{{ trans('label.keyword') }}" />
                            <span class="form-tips">{{ trans('message.keyword') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site-description" class="col-sm-2 control-label">{{ trans('label.site_desc') }}</label>
                        <div class="col-sm-8">
                            <input type="text" name="description" value="{% if options is not empty %}{{options['site_description']['op_value']}}{% endif %}"
                                   class="form-control" id="site-description" placeholder="{{ trans('label.site_desc') }}" />
                            <span class="form-tips">{{ trans('message.site_desc') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site_script_head" class="col-sm-2 control-label">{{ trans('label.site_script_head') }}</label>
                        <div class="col-sm-8">
                            <textarea type="text" name="site_script_head"
                                   class="form-control" id="site_script_head">{% if options is not empty %}{{options['site_script_head']['op_value']}}{% endif %}</textarea>
                            <span class="form-tips">{{ trans('message.site_script_head') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site_script_body" class="col-sm-2 control-label">{{ trans('label.site_script_body') }}</label>
                        <div class="col-sm-8">
                            <textarea type="text" name="site_script_body"
                                   class="form-control" id="site_script_body">{% if options is not empty %}{{options['site_script_body']['op_value']}}{% endif %}</textarea>
                            <span class="form-tips">{{ trans('message.site_script_body') }}</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <button type="submit" id="base-options-btn" class="btn btn-info btn-sm">{{ trans('label.save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="tab-pane fade" id="panelhome">
                <form action="{{url('options/savehomeconfig')}}" method="post" class="form-horizontal" id="base-options-form">
                    <div class="form-group">
                        <label for="site-name" class="col-sm-2 control-label">{{ trans('label.panel-home') }} 1</label>
                        <div class="col-sm-8">
                            <input type="text" name="home_tab_1" value="{% if options is not empty %}{{options['home_tab_1']['op_value']}}{% endif %}"
                                   class="form-control" id="home_tab_1" placeholder="{{ trans('label.panel-home') }} 1">
                            <span class="form-tips">3 ID danh mục sẽ hiển thị trên tab đầu tiên trang chủ</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site-name" class="col-sm-2 control-label">{{ trans('label.panel-home') }} 2</label>
                        <div class="col-sm-8">
                            <input type="text" name="home_tab_2" value="{% if options is not empty %}{{options['home_tab_2']['op_value']}}{% endif %}"
                                   class="form-control" id="home_tab_2" placeholder="{{ trans('label.panel-home') }} 2">
                            <span class="form-tips">6 ID danh mục sẽ hiển thị trên 2 tab kế tiếp trang chủ</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="site-name" class="col-sm-2 control-label">{{ trans('label.panel-home') }} 3</label>
                        <div class="col-sm-8">
                            <input type="text" name="home_tab_3" value="{% if options is not empty %}{{options['home_tab_3']['op_value']}}{% endif %}"
                                   class="form-control" id="home_tab_3" placeholder="{{ trans('label.panel-home') }} 3">
                            <span class="form-tips">6 ID danh mục sẽ hiển thị trên 2 tab cuối trang chủ</span>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-5">
                            <button type="submit" class="btn btn-info btn-sm">{{ trans('label.save') }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function open_popup(url){
        var w=880;
        var h=570;
        var l=Math.floor((screen.width-w)/2);
        var t=Math.floor((screen.height-h)/2);
        var win=window.open(url,'LCDFilemanager',"scrollbars=1,width="+w+",height="+h+",top="+t+",left="+l);
    }
    $('#base-options-btn').on('click', function(){
        var siteName = $.trim($('#site-name').val());
        var siteNamePattern = /^[\u4e00-\u9fa5\w-]+$/i;
        if(!siteNamePattern.test(siteName)){
            tips_message("{{ trans('label.site_name') }} {{ trans('label.alpha_numeric_dash') }}");
            return false;
        }

        $('#base-options-form').submit();
    });
</script>