<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="javascript:void(0);">{{ trans('site-setting') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            {{ trans('site-setting') }}
            <small>
                <i class="fa fa-angle-double-right"></i>
                {{ trans('view-setting') }}
            </small>
        </h1>
    </div>
    <div class="col-lg-12">
        <form action="{{url('options/saveread')}}" method="post" class="form-horizontal" id="saveread-options-form">
            <div class="form-group">
                <label for="page_default_number" class="col-sm-2 control-label">{{ trans('label.page_default_number') }}</label>
                <div class="col-sm-8">
                    <input type="text" name="page_default_number" value="{% if options is not empty %}{{options['page_default_number']['op_value']}}{% endif %}"
                           class="form-control" id="page_default_number" placeholder="{{ trans('label.page_default_number') }}">
                    <span class="form-tips">{{ trans('message.page_default_number') }}</span>
                </div>
            </div>
            <div class="form-group">
                <label for="page_article_number" class="col-sm-2 control-label">{{ trans('label.page_article_number') }}</label>
                <div class="col-sm-8">
                    <input type="text" name="page_article_number" value="{% if options is not empty %}{{options['page_article_number']['op_value']}}{% endif %}"
                           class="form-control" id="page_article_number" placeholder="{{ trans('label.page_article_number') }}">
                    <span class="form-tips">{{ trans('message.page_article_number') }}</span>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <button type="submit" id="read-options-btn" class="btn btn-info btn-sm">{{ trans('label.save') }}</button>
                </div>
            </div>
        </form>
    </div>
</div>