<div class="breadcrumbs" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="icon-home home-icon"></i>
            <a href="{{ url('dashboard/index') }}">{{ trans('dashboard') }}</a>
        </li>
        <li>
            <a href="{{ url('access/index') }}">{{ trans('access-management') }}</a>
        </li>
    </ul>
</div>
<div class="page-content">
    <div class="page-header">
        <h1>
            <a href="{{ url('access/index') }}">{{ trans('access-management') }}</a>
            <small>
                <i class="fa fa-angle-double-right"></i>
                {{ trans('list') }}
            </small>
        </h1>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <form class="form-horizontal" role="form">
                <div class="form-group">
                    <div class="col-sm-3">
                        <div class="input-group">
                            <input type="text" name="keyword" class="form-control" placeholder="{{ trans('label.keyword') }}" {% if keyword is not empty %}value="{{keyword}}"{% endif %} />
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-sm">
                                    {{ trans('label.search') }}
                                    <i class="icon-search icon-on-right bigger-110"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="btn-panel">
                            <a href="{{ url('access/write') }}" class="btn btn-success btn-sm" role="button">{{ trans('label.add-access') }}</a>
                        </div>
                    </div>
                </div>
            </form>
            <div class="table-responsive">
                <table class="table tree-grid table-striped table-bordered table-condensed table-hover" id="test-table">
                    <thead>
                        <tr>
                            <th>{{ trans('label.id') }}</th>
                            <th>{{ trans('label.name') }}</th>
                            <th>{{ trans('label.active') }}</th>
                            <th>{{ trans('label.version') }}</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    {% if access is not empty %}
                        <tbody>
                            {% for access in access %}
                                <tr>
                                    <td>
                                        {{access['id']}}
                                    </td>
                                    <td>
                                        <a href="{{ url('access/write?accessID='~access['id']) }}" title="{{ trans('label.edit') }}">
                                            {{access['name']}}
                                        </a>
                                        
                                    </td>
                                    <td>
                                        {% if access['active'] == 0 %}
                                            <span class="label label-white middle">
                                                <s>{{ trans('label.inactive') }}</s>
                                            </span>
                                        {% else %}
                                            <span class="label label-success label-white middle">
                                                {{ trans('label.active') }}
                                            </span>
                                        {% endif %}
                                    </td>
                                    <td>{{access['version']}}</td>
                                    <td>
                                        <a class="btn btn-xs btn-info" href="{{ url('access/write?accessID='~access['id']) }}" title="{{ trans('label.edit') }}">
                                            <i class="fa fa-pencil bigger-120"></i>
                                        </a>
                                        <button class="btn btn-xs btn-danger delete-access" data-url="{{ url('access/delete?accessID='~access['id']) }}" title="{{ trans('label.delete') }}">
                                            <i class="fa fa-trash-o bigger-120"></i>
                                        </button>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    {% else %}
                        <tbody>
                        <tr>
                            <td colspan="5">{{ trans('label.no-data') }}</td>
                        </tr>
                        </tbody>
                    {% endif %}
                </table>
                {% if access is not empty %}
                    {{ partial('public/paginator') }}
                {% endif %}
            </div>
        </div>
    </div>
</div>
<script>
    $('.delete-access').on('click', function(){
        var dataUrl = $.trim($(this).attr('data-url'));
        if(!window.confirm("{{ trans('alert.is-delete-selected') }}")){
            return false;
        }
        window.location.href = dataUrl;
    });
</script>